FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /source

COPY Receive.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app .
RUN ls -la
ENTRYPOINT ["dotnet", "Receive.dll"]

